### ISSUE TITLE
Missing ROS message while converting into pcd files using the pointcloud to pcd command

### ISSUE THREAD

**Issue by ethan20120** [ouster-lidar/ouster_example#105]
Hi,

Can any one please  guide me whether  anyone facing this issue?

When I am generating pcd file from the rosbag using the pointcloud to pcd command I am getting less pcd file comparing to the number of the ros message. However, when I am using the bag to pcd command I am getting the exact number of pcd file with respect to the ros message.

Anyone facing this same issue ?

Any suggestion will be very helpful.

Thanks

**Comment by dsb6063** [comment]
It sounds like the conversion is being downsampled. Could you send both commands. 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by dsb6063** [comment]
I did not see any downsample option for the standard command. If you are running just the standard command, then the other comment was correct. The data is being dropped. I don’t see any easy method to prevent the buffer overflow other than modifying the source code. If you are retrieving all the data from the sensor, then you should not have a problem on the conversion. Anyways I have attached a few approaches while you are troubleshooting.

An option would be to split your rosbag into sections that will complete before dropping data. If you can determine how long into the session before the data is being dropped, then you can split prior to any data loss. This would be specific to your setup. Obviously, it could be a tedious process and still may drop data, since it is an estimation of when the data starts being dropped.

I have attached a few commands when you split up the rosbag into manageable sections to assist slowing the data rate and preventing any packets from being dropped during recording the new bags. 

--queue=SIZE 

*	Use an outgoing queue of size SIZE (defaults to 0. As of 1.3.3 defaults to 100). 

$ rosbag play --queue=1000 recorded1.bag

--clock 

*	Publish the clock time 

$ rosbag play --clock recorded1.bag

--hz=HZ 

*	Publish clock time at frequency HZ Hz (default: 100). 

$ rosbag play --clock --hz=200 recorded1.bag

-d SEC, --delay=SEC 

*	Sleep SEC seconds after every advertise call (to allow subscribers to connect). 

$ rosbag play -d 5 recorded1.bag

 

 

Last Option

 

Level of effort (High)

 

Download the source for pcl_rosbag_to_pcd or point clouds below. Notice the loop_rate(4).

	

Debug the code. Run the first 10 messages. Compare with your first 10 messages header timestamps on the corresponding rosbag using rostopic echo -n10 /topic_name

 

http://wiki.ros.org/pcl_ros

 

The publisher is publishing into a topic at 4 hertz in this snippet 

 

  19 <http://wiki.ros.org/pcl_ros#CA-226070dcbe48ef19c444eb4914084fc903868f16_19>    ros::Rate loop_rate(4); loop_rate is the frequency in Hz (messages / second)


 

4 messages a second seems reasonable to not overflow and lose data.

 

 

 

 



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
