### ISSUE TITLE
Automated projection

### ISSUE THREAD

**Issue by ethan20120** [ouster-lidar/ouster_example#163]
Hi,
Can anyone please help me with the following issue?

I have many csv files containing the point cloud collected from the ouster lidar. Now I want to project the coordinate system into WGS 1984 of these point clouds. Is there any platform that can automatically do this for all of the files?

Thanks

**Comment by dsb6063** [comment]
How was the data collected? Did you collect from while stationary for each point? Then export to csv for each station. If this is the case, then the following steps could be used:


  1.  Pre-process the data to remove outliers.
  2.  Have known GPS lat/lon and coordinates for each point? Then, an association to the range data from the ouster can be done.

However, it does sound like you may have been moving while collecting. In this case, did the data get stitched together into one point cloud or several individual clouds? This is the typical collection that users want to perform SLAM on the data.

CloudCompare is an open source platform that may help. Otherwise, you will need to manually combine the individual point clouds using PCL.



________________________________
