### ISSUE TITLE
3D SLAM with OS-1

### ISSUE THREAD

**Issue by jattiogbe** [ouster-lidar/ouster_example#31]
Hi everyone,

Has anyone managed to apply SLAM and produce an actual 3D pointcloud using Ouster's OS-1 Lidar ? 
I am currently browsing to find a solution that creates not only floor maps but 3D models that I could work with as .ply, .asc file.

If you've got the solution and if you're kind enough to share it, I'll be the happiest guy !

**Comment by dsb6063** [comment]
Yes, lookup google cartographer. Search the cartographer boards for Ouster. An Ouster engineer has a workflow posted. Keep in mind the 16 channel will most likely need to be configured to generate more data. You will see similar configurations with Velodyne 16  channel where they have implemented two sensors with one horizontal and the other vertical to generate enough data for the 3D SLAM to work.

**Comment by jattiogbe** [comment]
Ok great, thank you.
[Here is ](https://github.com/googlecartographer/cartographer_ros/issues/1088) the discussion mentionned.
I will have a look at it quite soon.

What do you mean by configuring the lidar to generate more data ? because of its 30° vertical field of view ?

**Comment by dsb6063** [comment]
The FOV is one aspect, but the 3D SLAM algorithm needs an adequate flow of data to determine the pose of the robot. To help supply more data down the pipe, you can increase the resolution or / and increase the rotation rate (20 hz). I believe the manual mentions the performance vs quality and data loss. It does come down to tuning the configuration to the project needs. It may not be a factor indoors with defined corners. However, the posts have mentioned outdoor projects need a vertical sensor to establish enough points to establish a  consistent “z” value since the OS-1 has 16 channels with a 30 degree FOV. It may not be enough points to consistently generate quality maps.

 

Keep that in mind while you are testing. If you have issues, then try those adjustments mentioned above. I have not read any best practices with the Ouster sensor yet. That would be helpful.
