### ISSUE TITLE
Ouster's IMU type and extrinsics

### ISSUE THREAD

**Issue by yashmotorai** [ouster-lidar/ouster_example#382]
Hello Guys,
I have a couple of doubts. I read section 301 of the software user manual for ouster sensors. I have some doubts about transformation. I read that sensor's x=axis is pointing forward in the way that the external connector is located in the negative x-direction. I understand that. How about the accelerometer's x-direction. Does it have the same orientation as that of the sensor? This means, Is the x-axis of the accelerometer is parallel to the sensor's x-axis? I know for sure there is a translation between Imu and the sensor frame. So is the output of IMU data in the IMU frame or sensor frame? If it's in the IMU frame, Can you please show me how to transform it into the sensor frame(the accelerometer and gyroscope data)?

Furthermore, I want to calculate the IMU data with respect to the world frame. Can you please tell me the IMU type from one of the below options?

For NED type IMUs, the orientation of the world frame is x-north, y-east, z-down, relative to magnetic north.
For ENU type IMUs, the orientation of the world frame is x-east, y-north, z-up, relative to magnetic north.

Thank you,
Best Regards,
Yash

**Comment by kairenw** [comment]
Hi @yashmotorai, 

The output of the IMU data is in IMU frame. And yes: currently in all models it shares the same orientation as that of the sensor, sot hat the x-axis is parallel to the sensor's x-axis (in the 'sensor frame') and so on for the other two axes. You can tell since the transformation matrix we provide has an Identity in the rotation part.

In psuedocode, if you want an imu measurement, say the accel readings, in the sensor coordinate frame:
```
# make acceleration in 4 x 1 vector representing accel with 1 at the bottom for ease of multiplication with transform
accel_imu_frame = [ x_accel; y_accel, z_accel; 1] 

# M_imu_to_sensor is the 4x4 transform defined on page 24
accel_sensor_frame = M_imu_to_sensor_transform * accel_imu_frame 
```

For questions about our IMU type (NED or ENU), please contact [Ouster support](https://ouster.atlassian.net/servicedesk/customer/portal/8). 

Thanks! Closing this issue now.
