### ISSUE TITLE
everytime pointcloud2.data z is zero

### ISSUE THREAD

**Issue by havvanurbozomeroglu** [ouster-lidar/ouster_example#385]
Hi, 

 ```
   max_deg = int(360 // sample_rate)
    arr = pointcloud2_to_xyz_array(msg)

    angle = np.arctan2(arr[:, 1], arr[:, 0])
    angle = np.rad2deg(angle) + 180
    angle /= sample_rate
    angle = np.round(angle)
    angle[angle > max_deg - 1] = max_deg - 1

    dist = np.sqrt(arr[:, 0] ** 2 + arr[:, 1] ** 2)
    min_dist = np.ones(max_deg) * max_dist
    for i, ang in enumerate(angle):
        if min_dist[int(ang)] > dist[i]:
            min_dist[int(ang)] = dist[i]
    # -- make angle based min_distance data -- end

    # -- to pointcloud for visualization
    out_angle = np.deg2rad(np.linspace(0, 359, max_deg))
    out_x = -np.cos(out_angle) * min_dist
    out_y = -np.sin(out_angle) * min_dist
    out_z = np.zeros(max_deg)
    out_cloud = np.stack([out_x, out_y, out_z], axis=-1)

    print(out_z)
```
output: 
`[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]
`

print(out_x)

output: 
`[-0.         -0.30125702  0.30265708  0.99996192  0.         -0.30468984
 -0.        ]
[-0.         -0.30637342  0.28919702  0.99996192  0.         -0.30468984
 -0.        ]
[-0.         -0.31355883  0.30099976  0.99996192  0.         -0.30612661
 -0.        ]
[-0.         -0.30135081  0.28919702  0.99996192  0.         -0.29824787
 -0.        ]`

ı use ouster os1. Thanks in advance

**Comment by kairenw** [comment]
Hi @havvanurbozomeroglu,

It's a little hard to understand what you're doing. For instance, on the first line, what is `sample_rate`? Often times, the sample rate is 10 or 20 Hz (10 or 20 samples of clouds a second). However, given the way you're calculating the `max_deg`, it seems you'd want the number of columns per scan (likely 1024 or 2048). But plugging that in would give you 0 for `max_deg` no matter what. It's also hard to understand what you want as the format of your `out_x` and `out_z`: why do you need these to be 2d arrays?

In any case, I think that `out_z` is all 0s because you're telling it to be with:
` out_z = np.zeros(max_deg)`

It looks like you're trying to get the XYZ coordinates of a single packet message. We recommend you use our `LidarScan` class: This [link](https://static.ouster.dev/sdk-docs/reference/lidar-scan.html#projecting-into-cartesian-coordinates) should show you how to use our Python SDK to obtain the XYZ coordiantes of a batched scan. Each message should be `columns_per_packet` number of columns from the batched scan.

If you're uncomfortable doing it that way, you can also calculate the XYZ coordinates by hand. In that case, you may find the reference calculations here helpful: https://github.com/ouster-lidar/ouster_example/blob/master/python/src/ouster/sdk/examples/reference.py#L17.

Hope that helps.
