### ISSUE TITLE
can not get data from code 

### ISSUE THREAD

**Issue by JohnHe12** [ouster-lidar/ouster_example#427]
i use the ouster lidar and use the code from github,i set the upd_dest and sensor_ip , i can ping the lidar but from the code simple_viz or roslaunch to start, it shows nothing and the messages in the topic is empty.
so i use the wireshark to save pcap ,use open3d to viz, it shows the pointcloud ,so it does send the data to the port. and webgui has no error. and then i use my another laptop under the same internet, it works! so same internet, same code , same lidar ,of course i check the different ip from computer , but my computer can not viz nor publish. it very confused me.

**Comment by Samahu** [comment]
Hi @JohnHe12, are you using the latest version of the example, can you share the logs from the ROS launch command?

**Comment by JohnHe12** [comment]
@Samahu ,because i use the FW 2.1.3 so i use the corresponding example 20210608 and the launch file on the laptop and computer is the same.follow is my launch file. what confused me is that the same environment in laptop and computer . last week my computer could receive the data, after i set up the NTP and change the GPU, it didn't work until now.
<img width="520" alt="截屏2022-08-31 17 32 24" src="https://user-images.githubusercontent.com/93966260/187718733-e6249d63-3698-4ab5-b140-056248238f45.png">

**Comment by Samahu** [comment]
You could still upgrade to the last SDK release (if you wish). The last software release named FW 2.4 supports FW 2.0 and higher. Upgrading may or may not help with your case.

I asked for the output of the launch command, meaning what is the console output after you execute `roslaunch ouster_ros ...`.

Since you mentioned that the same code works on a different machine, I feel the problem you are dealing with is specific to your computer/sensor/network setup rather than a problem with the code. You may want to reach to [our customer support team](https://ouster.atlassian.net/servicedesk/customer/portal/8) for this kind of issues.

**Comment by JohnHe12** [comment]
@Samahu Yeah i totally agree with you , and i have already read the document and i don't find the solution.because i can ping the lidar.

**Comment by kairenw** [comment]
Is it possible you've got a firewall on?

**Comment by JohnHe12** [comment]
@kairenw ufw is on, you mean i need to turn off firewall first?

**Comment by kairenw** [comment]
yes that's correct (and restart!)

**Comment by JohnHe12** [comment]
@kairenw i sove the problem , it's the firewall problem!!!!! thanks very much.

**Comment by kairenw** [comment]
Oh, great! I'm so glad. Sorry I didn't get back to you in time to confirm. Glad it got fixed.

Closing this ticket now
