### ISSUE TITLE
Issue reading pointCloud in Matlab

### ISSUE THREAD

**Issue by 21Ansh** [ouster-lidar/ouster_example#45]
I am using rosrun pcl_ros pointcloud_to_pcd input:=/ouster/points for saving point cloud to pcd files coming from rosbag. When I tried to read these pcd files in matlab using pcread I got following output

![PointCloud](https://user-images.githubusercontent.com/12714762/54735947-ca3f4100-4bce-11e9-90e3-b720d0787c46.png)

![Images](https://user-images.githubusercontent.com/12714762/54735989-f5299500-4bce-11e9-9af5-ef1d03d57c35.png)

I cannot make any sense out of these images.

**Comment by daniel-lawrence-lu** [comment]
Try reshaping the images to `[1024, 64]` instead of `[64, 1024]`.

**Comment by 21Ansh** [comment]
tried, not working and ideally, it should be 64,1024 because vertical resolution of ouster lidar is 64.

**Comment by dgarbuzov** [comment]
The issue is that the point clouds follow the staggered firing pattern of the sensor and are not arranged in columns according to the azimuth angle as you expect.

You can infer how this works from the angle offsets described in the user guide, but it might be easier to just look at the sample code that produces ROS image message output:

https://github.com/ouster-lidar/ouster_example/blob/4ce8e4ff7e4960bf6bc356e0c590ce2df404835f/ouster_ros/src/img_node.cpp#L88-L103

Hope that helps!

**Comment by jattiogbe** [comment]
Hello @21Ansh ,

Did you solve your case using Matlab ?
I have an OS-1.16, and I am a beginner in Matlab, so I'm thinking about the use of both together.

Thank you.
